// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTge0ILdLQL5bb00FStM2MIM6Uuv1Iues',
    appId: '1:1018852082165:web:dfb35e6b61e0d41f8160bc',
    messagingSenderId: '1018852082165',
    projectId: 'login-32691',
    authDomain: 'login-32691.firebaseapp.com',
    storageBucket: 'login-32691.appspot.com',
    measurementId: 'G-075HTEBE86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMLkKLsOFYB-WnPTD1VLoc-pRdJOOMsAo',
    appId: '1:1018852082165:android:d64adbf6d622bec98160bc',
    messagingSenderId: '1018852082165',
    projectId: 'login-32691',
    storageBucket: 'login-32691.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF-2eoJIUx8m3XoNrjUbgqZrXVYbGLTb8',
    appId: '1:1018852082165:ios:6267006ebdd6d2748160bc',
    messagingSenderId: '1018852082165',
    projectId: 'login-32691',
    storageBucket: 'login-32691.appspot.com',
    iosClientId: '1018852082165-hgfel9holso5f1qb6gsfiln9s69tj79h.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF-2eoJIUx8m3XoNrjUbgqZrXVYbGLTb8',
    appId: '1:1018852082165:ios:6267006ebdd6d2748160bc',
    messagingSenderId: '1018852082165',
    projectId: 'login-32691',
    storageBucket: 'login-32691.appspot.com',
    iosClientId: '1018852082165-hgfel9holso5f1qb6gsfiln9s69tj79h.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectLogin',
  );
}
